### ISSUE TITLE
GitHub ActionsでのNode.js 12の非推奨対応

### ISSUE THREAD

**Issue by kaitas** [vvakame/docker-review#78]
後続の `checkout@v2` で 以下のような警告が表示されるようになりました

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/upload-artifact, actions/checkout

checkoutにはv3が出ています
https://github.com/actions/checkout

```
jobs:
  build:
    name: Re:VIEW Workflow
    runs-on: ubuntu-latest
    container: docker://vvakame/review:5.5
    steps:
      - uses: actions/checkout@v3
      - name: Build PDF and Epub
        run: rake all
      - uses: actions/upload-artifact@v3
```
といった感じで @v2 を @v3 にしていただけるとよいと思います
